# Icons: https://github.com/StorageB/icons/blob/main/GNOME48Adwaita/icons.md

name = "system"
name_pretty = "System"
global_search = false
fixed_order = true
icon = "system-lock-screen"

[[entries]]
icon = "system-lock-screen"
text = "Lock"
actions = { "lock" = "playerctl pause; hyprlock" }

[[entries]]
icon = "view-conceal-symbolic"
text = "Suspend"
actions = { "suspend" = "playerctl pause; systemctl suspend" }

[[entries]]
icon = "system-log-out"
text = "Relaunch"
actions = { "relaunch" = "uwsm stop" }

[[entries]]
icon = "system-reboot"
text = "Restart"
actions = { "restart" = "systemctl reboot" }

[[entries]]
icon = "system-shutdown"
text = "Shutdown"
actions = { "shutdown" = "systemctl poweroff" }
