[config]

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.cache/theming/alacritty.toml'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.cache/theming/btop.theme'

[templates.hypr]
input_path = '~/.config/matugen/templates/hypr.conf'
output_path = '~/.cache/theming/hypr.conf'

[templates.css-colors]
input_path = '~/.config/matugen/templates/css-colors.css'
output_path = '~/.cache/theming/css-colors.css'

# Template dummy file to run hook as css-colors template is used
[templates.waybar]
input_path = '~/.config/matugen/templates/dummy.txt'
output_path = '/dev/null'
post_hook = 'pkill -SIGUSR2 waybar'

# Template dummy file to run hook as css-colors template is used
[templates.swayosd]
input_path = '~/.config/matugen/templates/dummy.txt'
output_path = '/dev/null'
post_hook = 'systemctl --user try-restart swayosd'

# Template dummy file to run hook as css-colors template is used
[templates.walker]
input_path = '~/.config/matugen/templates/dummy.txt'
output_path = '/dev/null'
post_hook = 'systemctl --user try-restart walker'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux.conf'
output_path = '~/.cache/theming/tmux.conf'
post_hook = 'tmux source-file ~/.config/tmux/tmux.conf'

[templates.gtk]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.cache/theming/gtk.css'
post_hook = '~/.config/matugen/trigger_gtk.sh'
