local wezterm = require('wezterm')
-- Plain table instead of wezterm.config_builder() because it causes very
-- slow config reloads. What it doesn't do is validate config.
local config = {}

config.font = wezterm.font('JetBrains Mono')

-- generated by the matugen/noctalia template into ~/.cache/theming/wezterm
config.color_scheme_dirs = { wezterm.home_dir .. '/.cache/theming/wezterm' }
config.color_scheme = 'Noctalia'
config.window_background_opacity = 0.8
config.text_background_opacity = 0.8

config.default_cursor_style = 'SteadyBar'

config.audible_bell = 'Disabled'
config.visual_bell = {
    fade_in_function = 'Ease',
    fade_in_duration_ms = 60,
    fade_out_function = 'Ease',
    fade_out_duration_ms = 200,
}
-- The default 10fps draws the bell in two or three steps
config.animation_fps = 60
local ok, scheme = pcall(wezterm.color.load_scheme, config.color_scheme_dirs[1] .. '/Noctalia.toml')
if ok then
    config.colors = { visual_bell = tostring(wezterm.color.parse(scheme.background):lighten(0.01)) }
end

config.window_padding = { left = 0, right = 0, top = 0, bottom = 0 }

-- Do not use custom ssh-agent
config.mux_enable_ssh_agent = false

-- tmux-style tab bar, coloured from config.color_scheme
require('tabbar').apply_to_config(config)

require('keys').apply_to_config(config)

-- CTRL-SHIFT-E: resize the tab's panes to equal widths
require('equalize').apply_to_config(config)

-- tmux-style C-b prefix bindings, passed through when tmux is running
require('tmux').apply_to_config(config)

-- Needs to be after other key bindings
require('smart-splits').apply_to_config(config)

require('local').apply_to_config(config)

return config
