local wezterm = require('wezterm')
-- Plain table instead of wezterm.config_builder() because it causes very
-- slow config reloads. What it doesn't do is validate config.
local config = {}

config.font = wezterm.font('JetBrains Mono')

-- generated by the matugen/noctalia template into ~/.cache/theming/wezterm
config.color_scheme_dirs = { wezterm.home_dir .. '/.cache/theming/wezterm' }
config.color_scheme = 'Noctalia'
config.window_background_opacity = 0.8

-- tmux-style tab bar, coloured from config.color_scheme
require('tabbar').apply_to_config(config)

require('keys').apply_to_config(config)

-- Needs to be after other key bindings
require('smart-splits').apply_to_config(config)

return config
