# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/

################################################################################
###                                  DEBUG                                   ###
################################################################################

# Enable hyprland debug logs
# Saved to "$XDG_RUNTIME_DIR/hypr/$(ls -t $XDG_RUNTIME_DIR/hypr/ | head -n 1)/hyprland.log"
#
# debug:disable_logs=false

################################################################################
###                             EXTERNAL CONFIG                              ###
################################################################################

source = ~/.cache/theming/hypr.conf

# Source local config
source = ~/.config/hypr/hyprland/local/*.conf

# Source split config
source = ~/.config/hypr/hyprland/env.conf
source = ~/.config/hypr/hyprland/startup.conf
source = ~/.config/hypr/hyprland/keybindings.conf
source = ~/.config/hypr/hyprland/windows.conf
source = ~/.config/hypr/hyprland/input.conf
source = ~/.config/hypr/hyprland/misc.conf
source = ~/.config/hypr/hyprland/tiling.conf
source = ~/.config/hypr/hyprland/look.conf

# Setup clamshell, should be sourced after local to populate screen variables
source = ~/.config/hypr/hyprland/clamshell.conf
