# Auto-generated by Matugen

local M = {}

M.primary    = "{{ colors.primary.default.rgb | replace: " ", "" }}"
M.secondary  = "{{ colors.secondary.default.rgb | replace: " ", "" }}"
M.outline    = "{{ colors.outline.default.rgb | replace: " ", "" }}"
M.error      = "{{ colors.error.default.rgb | replace: " ", "" }}"

M.surface        = "{{ colors.surface.default.rgb | replace: " ", "" }}"
M.surfaceVariant = "{{ colors.surface_variant.default.rgb | replace: " ", "" }}"

M.onSurface        = "{{ colors.on_surface.default.rgb | replace: " ", "" }}"
M.onSurfaceVariant = "{{ colors.on_surface_variant.default.rgb | replace: " ", "" }}"

return M
