# Auto-generated by Matugen

--- Material You roles for the Hyprland Lua config.
--- Every role Matugen emits is exported, so `look.lua` can always pair a
--- background with its matching `on*` foreground instead of guessing.

local M = {}

-- Primary
M.primary               = "{{ colors.primary.default.rgb | replace: " ", "" }}"
M.onPrimary             = "{{ colors.on_primary.default.rgb | replace: " ", "" }}"
M.primaryContainer      = "{{ colors.primary_container.default.rgb | replace: " ", "" }}"
M.onPrimaryContainer    = "{{ colors.on_primary_container.default.rgb | replace: " ", "" }}"
M.primaryFixed          = "{{ colors.primary_fixed.default.rgb | replace: " ", "" }}"
M.primaryFixedDim       = "{{ colors.primary_fixed_dim.default.rgb | replace: " ", "" }}"
M.onPrimaryFixed        = "{{ colors.on_primary_fixed.default.rgb | replace: " ", "" }}"
M.onPrimaryFixedVariant = "{{ colors.on_primary_fixed_variant.default.rgb | replace: " ", "" }}"
M.inversePrimary        = "{{ colors.inverse_primary.default.rgb | replace: " ", "" }}"

-- Secondary
M.secondary               = "{{ colors.secondary.default.rgb | replace: " ", "" }}"
M.onSecondary             = "{{ colors.on_secondary.default.rgb | replace: " ", "" }}"
M.secondaryContainer      = "{{ colors.secondary_container.default.rgb | replace: " ", "" }}"
M.onSecondaryContainer    = "{{ colors.on_secondary_container.default.rgb | replace: " ", "" }}"
M.secondaryFixed          = "{{ colors.secondary_fixed.default.rgb | replace: " ", "" }}"
M.secondaryFixedDim       = "{{ colors.secondary_fixed_dim.default.rgb | replace: " ", "" }}"
M.onSecondaryFixed        = "{{ colors.on_secondary_fixed.default.rgb | replace: " ", "" }}"
M.onSecondaryFixedVariant = "{{ colors.on_secondary_fixed_variant.default.rgb | replace: " ", "" }}"

-- Tertiary
M.tertiary               = "{{ colors.tertiary.default.rgb | replace: " ", "" }}"
M.onTertiary             = "{{ colors.on_tertiary.default.rgb | replace: " ", "" }}"
M.tertiaryContainer      = "{{ colors.tertiary_container.default.rgb | replace: " ", "" }}"
M.onTertiaryContainer    = "{{ colors.on_tertiary_container.default.rgb | replace: " ", "" }}"
M.tertiaryFixed          = "{{ colors.tertiary_fixed.default.rgb | replace: " ", "" }}"
M.tertiaryFixedDim       = "{{ colors.tertiary_fixed_dim.default.rgb | replace: " ", "" }}"
M.onTertiaryFixed        = "{{ colors.on_tertiary_fixed.default.rgb | replace: " ", "" }}"
M.onTertiaryFixedVariant = "{{ colors.on_tertiary_fixed_variant.default.rgb | replace: " ", "" }}"

-- Error
M.error            = "{{ colors.error.default.rgb | replace: " ", "" }}"
M.onError          = "{{ colors.on_error.default.rgb | replace: " ", "" }}"
M.errorContainer   = "{{ colors.error_container.default.rgb | replace: " ", "" }}"
M.onErrorContainer = "{{ colors.on_error_container.default.rgb | replace: " ", "" }}"

-- Surface
M.surface                 = "{{ colors.surface.default.rgb | replace: " ", "" }}"
M.onSurface               = "{{ colors.on_surface.default.rgb | replace: " ", "" }}"
M.surfaceVariant          = "{{ colors.surface_variant.default.rgb | replace: " ", "" }}"
M.onSurfaceVariant        = "{{ colors.on_surface_variant.default.rgb | replace: " ", "" }}"
M.surfaceDim              = "{{ colors.surface_dim.default.rgb | replace: " ", "" }}"
M.surfaceBright           = "{{ colors.surface_bright.default.rgb | replace: " ", "" }}"
M.surfaceTint             = "{{ colors.surface_tint.default.rgb | replace: " ", "" }}"
M.surfaceContainerLowest  = "{{ colors.surface_container_lowest.default.rgb | replace: " ", "" }}"
M.surfaceContainerLow     = "{{ colors.surface_container_low.default.rgb | replace: " ", "" }}"
M.surfaceContainer        = "{{ colors.surface_container.default.rgb | replace: " ", "" }}"
M.surfaceContainerHigh    = "{{ colors.surface_container_high.default.rgb | replace: " ", "" }}"
M.surfaceContainerHighest = "{{ colors.surface_container_highest.default.rgb | replace: " ", "" }}"
M.inverseSurface          = "{{ colors.inverse_surface.default.rgb | replace: " ", "" }}"
M.inverseOnSurface        = "{{ colors.inverse_on_surface.default.rgb | replace: " ", "" }}"

-- Background
M.background   = "{{ colors.background.default.rgb | replace: " ", "" }}"
M.onBackground = "{{ colors.on_background.default.rgb | replace: " ", "" }}"

-- Outline & effects
M.outline        = "{{ colors.outline.default.rgb | replace: " ", "" }}"
M.outlineVariant = "{{ colors.outline_variant.default.rgb | replace: " ", "" }}"
M.shadow         = "{{ colors.shadow.default.rgb | replace: " ", "" }}"
M.scrim          = "{{ colors.scrim.default.rgb | replace: " ", "" }}"

return M
